[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython"
]
build-backend = "setuptools.build_meta"

[project]
name = "superintervals"
version = "0.2.0"
description = "Rapid interval intersections"
authors = [{name = "Kez Cleal", email = "clealk@cardiff.ac.uk"}]