[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython"
]
build-backend = "setuptools.build_meta"

[project]
name = "matrylist"
version = "0.1.0"
description = "Rapid interval intersections"
authors = [{name = "Kez Cleal", email = "clealk@cardiff.ac.uk"}]