from collections.abc import Callable
from collections.abc import Collection
from collections.abc import Iterable
from typing import Any

from typing_extensions import Buffer
from typing_extensions import Self
from typing_extensions import disjoint_base

__all__ = ["IntervalMap"]

@disjoint_base
class IntervalMap:
    """An interval map of end-inclusive integer intervals with associated Python objects."""

    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> tuple[int, int, Any]: ...
    def add(self, start: int, end: int, value: Any = None) -> None: ...
    @classmethod
    def from_arrays(
        cls,
        starts: Iterable[int] | Buffer,
        ends: Iterable[int] | Buffer,
        values: Collection[Any] | None = None,
    ) -> Self: ...
    def build(self) -> None: ...
    def at(self, index: int) -> tuple[int, int, Any]: ...
    def starts_at(self, index: int) -> int: ...
    def ends_at(self, index: int) -> int: ...
    def data_at(self, index: int) -> Any: ...
    def clear(self) -> None: ...
    def reserve(self, n: int) -> None: ...
    def size(self) -> int: ...
    def has_overlaps(self, start: int, end: int) -> bool: ...
    def count(self, start: int, end: int) -> int: ...
    def search_values(self, start: int, end: int) -> list[Any]: ...
    def search_idxs(self, start: int, end: int) -> list[int]: ...
    def search_keys(self, start: int, end: int) -> list[tuple[int, int]]: ...
    def search_items(self, start: int, end: int) -> list[tuple[int, int, Any]]: ...
    def coverage(self, start: int, end: int) -> tuple[int, int]: ...
    def count_batch(self, starts: Buffer, ends: Buffer) -> list[int]: ...
    def search_idxs_batch(self, starts: Buffer, ends: Buffer) -> list[list[int]]: ...
    def search_values_batch(self, starts: Buffer, ends: Buffer) -> list[list[Any]]: ...
    def merge_overlaps(self, combine: Callable[[Any, Any], Any] | None = None) -> IntervalMap: ...
    def union_with(
        self, other: IntervalMap, combine: Callable[[Any, Any], Any] | None = None
    ) -> IntervalMap: ...
    def intersection(
        self, other: IntervalMap, combine: Callable[[Any, Any], Any] | None = None
    ) -> IntervalMap: ...
    def difference(self, other: IntervalMap) -> IntervalMap: ...
    def symmetric_difference(self, other: IntervalMap) -> IntervalMap: ...
    def gaps(self, lo: int, hi: int, fill: Any = None) -> IntervalMap: ...
    def span(self) -> tuple[int, int] | None: ...
    def expand(
        self, left: int, right: int, lo: int | None = None, hi: int | None = None
    ) -> IntervalMap: ...
    def flank(
        self, left: int, right: int, lo: int | None = None, hi: int | None = None
    ) -> IntervalMap: ...
    def unique(self, combine: Callable[[Any, Any], Any] | None = None) -> IntervalMap: ...
