name: Sync R Package

on:
  push:
    branches: [ main ]
    paths: [ 'src/R/**' ]  # Only trigger when R code changes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for subtree
        token: ${{ secrets.PAT_TOKEN }}

    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add remote and push subtree
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git remote add superintervalsr https://x-access-token:${PAT_TOKEN}@github.com/kcleal/superintervalsr.git
        git subtree push --prefix=src/R superintervalsr main