name: Sync R Package

on:
  push:
    branches: [ main ]
    paths: [ 'src/R/**' ]  # Only trigger when R code changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for subtree
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Add remote and push subtree
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote add superintervals-r https://x-access-token:${GITHUB_TOKEN}@github.com/kcleal/superintervals-r.git
        git subtree push --prefix=src/R superintervals-r main
